set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
if has('win32')
  set rtp+=$HOME/vimfiles/bundle/Vundle.vim/
  call vundle#begin('$HOME/vimfiles/bundle/')
else
  set rtp+=~/.vim/bundle/Vundle.vim
  call vundle#begin()
endif

" Plugins:
Plugin 'bling/vim-airline'
Plugin 'airblade/vim-gitgutter'
Plugin 'fatih/vim-go'
Plugin 'scrooloose/syntastic'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-sleuth'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-session'
Plugin 'ekalinin/Dockerfile.vim'
Plugin 'scrooloose/nerdtree'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
filetype on
syntax enable

" use the system clipboard
if has('unix')
  set clipboard=unnamedplus
else
  set clipboard=unnamed
endif

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_go_checkers=['']

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" vim-airline
let g:airline#extensions#tabline#enabled = 1
set laststatus=2
let g:airline_powerline_fonts = 1

" vim-better-whitespace
autocmd FileType * autocmd BufWritePre <buffer> StripWhitespace

" CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

" vim-go
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

let g:go_fmt_command = "goimports"

" vim-rails
let g:rubycomplete_buffer_loading = 1
let g:rubycomplete_rails = 1

" vim-session
let g:session_autosave = 'yes'
let g:session_autoload = 'yes'
" do not persist font or color, too confusing
let g:session_persist_font = 0
let g:session_persist_colors = 0

" My Custom configs
set number " displays line numbers
set guioptions-=T "removes toolbar
set guioptions-=m "removes menu bar"
set ts=2 " Set tabs to 2 spaces
set sw=2
set wildmenu " Shows popup menu on <tab> completion

" Use spaces for ruby
autocmd FileType ruby set expandtab

" Map Ctrl + t to tooggle NERDTree
map <C-t> :NERDTreeToggle<CR>
" Ctrl + h go to previous buffer
nnoremap <C-h> :bp<CR>
" Ctrl + l go to next buffer
nnoremap <C-l> :bn<CR>
" Ctrl + q closes current buffer
nnoremap <C-q> :bd<CR>
" Ctrl + s saves current buffer
map <C-s> :w<CR>
" Ctrl + a select all
nnoremap <C-a> ggVG

"molokai color scheme
colorscheme molokai/colors/molokai

"bigger font
"set guifont=Monospace\ 11
if has('unix')
  set guifont=Ubuntu\ Mono\ derivative\ Powerline\ 14
else
  set guifont=Ubuntu_Mono_derivative_Powerlin:h12:cANSI
endif
